name: CentOS Stream 8
on:
  workflow_dispatch:
    inputs:
      zfs-version:
        required: true
        type: choice
        options: 
        - "2.0.6"
        - "2.1.1"
      kernel-version:
        required: true
      kernel-release:
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build RPMs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download OpenZFS source
        run: |
          source ./openzfs
          curl -sLO https://github.com/openzfs/zfs/releases/download/zfs-${{ github.event.inputs.zfs-version }}/zfs-${{ github.event.inputs.zfs-version }}.tar.gz
          tar xf zfs-${{ github.event.inputs.zfs-version }}.tar.gz
      - name: Pull conainer image
        run: |
          docker pull quay.io/centos/centos:stream8
      - name: Run conainer
        run: |
          docker run -d -v $(pwd)/zfs-${{ github.event.inputs.zfs-version }}:/srv/zfs --name builder quay.io/centos/centos:stream8 sleep 60m
      - name: Update conainer
        run: |
          docker exec builder dnf -qy update
      - name: Install kernel
        run: |
          docker exec builder dnf -y install\
           https://koji.mbox.centos.org/pkgs/packages/kernel/${{ github.event.inputs.kernel-version }}/${{ github.event.inputs.kernel-release }}.el8/noarch/kernel-abi-stablelists-${{ github.event.inputs.kernel-version }}-${{ github.event.inputs.kernel-release }}.el8.noarch.rpm\
           https://koji.mbox.centos.org/pkgs/packages/kernel/${{ github.event.inputs.kernel-version }}/${{ github.event.inputs.kernel-release }}.el8/x86_64/kernel-devel-${{ github.event.inputs.kernel-version }}-${{ github.event.inputs.kernel-release }}.el8.x86_64.rpm\
           https://koji.mbox.centos.org/pkgs/packages/kernel/${{ github.event.inputs.kernel-version }}/${{ github.event.inputs.kernel-release }}.el8/x86_64/kernel-headers-${{ github.event.inputs.kernel-version }}-${{ github.event.inputs.kernel-release }}.el8.x86_64.rpm
      - name: Install build dependencies
        run: |
          docker exec builder dnf -y --enablerepo=powertools install $(cat dependencies/rhel8)
      - name: Add build user
        run: |
          docker exec builder useradd mockbuild
      - name: Fix files ownership
        run: |
          docker exec builder chown -R mockbuild:mockbuild /srv/zfs
      - name: Configure OpenZFS
        run: |
          docker exec -u mockbuild -w /srv/zfs builder ./configure --with-spec=redhat
      - name: Build utils RPMs
        run:  |
          docker exec -u mockbuild -w /srv/zfs builder make -j1 rpm-utils
          docker exec -w /srv/zfs builder bash -c "rm -f ./*.src.rpm"
      - name: Build zfs-container RPM
        run: |
          source ./openzfs
          sed -i "s/ZFS_VERSION/${{ github.event.inputs.zfs-version }}/g" zfs-container.spec
          docker cp zfs-container.spec builder:/home/mockbuild/zfs-container.spec
          docker exec -u mockbuild -w /home/mockbuild builder rpmbuild -bb zfs-container.spec
          docker exec -u mockbuild -w /home/mockbuild builder mv ./rpmbuild/RPMS/noarch/zfs-container-${{ github.event.inputs.zfs-version }}-1.fc34.noarch.rpm /srv/zfs/
      - name: Add utils release
        run: |
          gh release create -t "OpenZFS ${{ github.event.inputs.zfs-version }}: CentOS Stream 8" --target ${GITHUB_SHA} v${{ github.event.inputs.zfs-version }}-centosstream8 zfs-${{ github.event.inputs.zfs-version }}/zfs*.rpm zfs-${{ github.event.inputs.zfs-version }}/lib*.rpm zfs-${{ github.event.inputs.zfs-version }}/python*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build kmod RPMs
        run: |
          docker exec -u mockbuild -w /srv/zfs builder make -j1 rpm-kmod
          docker exec -w /srv/zfs builder bash -c "rm -f ./*.src.rpm"
      - name: Add kmod release
        run: |
          gh release create -t "OpenZFS ${{ github.event.inputs.zfs-version }}: CentOS Stream 8 ${{ github.event.inputs.kernel-version }}-${{ github.event.inputs.kernel-release }}" --target ${GITHUB_SHA} v${{ github.event.inputs.zfs-version }}-centosstream8-${KERNEL_VERSION}-${KERNEL_RELEASE} zfs-${{ github.event.inputs.zfs-version }}/kmod*.rpm zfs-${{ github.event.inputs.zfs-version }}/zfs-kmod*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
